services:
  postgres:
    image: postgres:16-alpine
    container_name: sap_etl_postgres
    environment:
      POSTGRES_DB: sap_etl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
