-- 002_staging_tables.sql: Tablas de staging (raw y clean)

-- ============================================================
-- STAGING RAW: copia cruda del CSV, todo como TEXT
-- ============================================================

CREATE TABLE IF NOT EXISTS staging.stg_clientes_raw (
    _batch_id       VARCHAR(64)     NOT NULL,
    _row_number     INTEGER         NOT NULL,
    _loaded_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    col_cod_cliente             TEXT,
    col_nombre_sol              TEXT,
    col_cond_pago               TEXT,
    col_desc_cond_pag           TEXT,
    col_ramo                    TEXT,
    col_desc_ramo               TEXT,
    col_gr_clientes             TEXT,
    col_desc_gr_clien           TEXT,
    col_direccion               TEXT,
    col_telefono                TEXT,
    col_rif                     TEXT,
    col_ruta_transp             TEXT,
    col_poblacion               TEXT,
    col_zona_ventas             TEXT,
    col_desc_zona               TEXT,
    col_grupo_vend              TEXT,
    col_desc_grupo_ve           TEXT,
    col_descrip_estado          TEXT,
    col_fecha_creacion          TEXT,
    col_ag_ret                  TEXT,
    col_ult_fact                TEXT,
    col_fecha_fact              TEXT,
    col_doc_ult_pago            TEXT,
    col_fecha_pago              TEXT,
    col_nombre_contacto         TEXT,
    col_telefono_movil          TEXT,
    col_cod_vend                TEXT,
    col_nombre_vendedor         TEXT,
    col_cod_ger_reg             TEXT,
    col_nombre_gte_regional     TEXT,
    col_moneda                  TEXT,
    col_lista                   TEXT,
    col_denominacion            TEXT,
    col_canal                   TEXT,
    col_fecha_actual            TEXT,
    col_dias_ult_fact           TEXT,
    PRIMARY KEY (_batch_id, _row_number)
);

CREATE TABLE IF NOT EXISTS staging.stg_ventas_raw (
    _batch_id       VARCHAR(64)     NOT NULL,
    _row_number     INTEGER         NOT NULL,
    _loaded_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    col_razon_social            TEXT,
    col_gpo_cliente             TEXT,
    col_clase_doc               TEXT,
    col_num_factura             TEXT,
    col_sector                  TEXT,
    col_canal                   TEXT,
    col_fecha_doc               TEXT,
    col_zona_vtas               TEXT,
    col_almacen                 TEXT,
    col_denominacion_material   TEXT,
    col_cantidad_umv            TEXT,
    col_um_vtas                 TEXT,
    col_cantidad_umb            TEXT,
    col_um_base                 TEXT,
    col_prec_unitario           TEXT,
    col_monto_neto              TEXT,
    col_iva                     TEXT,
    col_importe_final           TEXT,
    col_doc_comercial           TEXT,
    col_cond_pago               TEXT,
    col_fec_venc                TEXT,
    col_moneda_doc              TEXT,
    col_status_anulacion        TEXT,
    col_doc_anulac              TEXT,
    col_grp_vend                TEXT,
    col_vendedor                TEXT,
    col_referencia              TEXT,
    col_pedido_vta              TEXT,
    col_jerarquia_1             TEXT,
    col_jerarquia_2             TEXT,
    col_jerarquia_3             TEXT,
    col_um_peso                 TEXT,
    col_peso_fact               TEXT,
    col_peso_total              TEXT,
    col_um_peso_gen             TEXT,
    col_ramo                    TEXT,
    col_gr_material             TEXT,
    col_gr_articulo             TEXT,
    col_tipo_cambio             TEXT,
    col_mes                     TEXT,
    col_ejercicio               TEXT,
    col_prec_unitario_2         TEXT,
    col_monto_neto_2            TEXT,
    col_iva_2                   TEXT,
    col_importe_final_2         TEXT,
    col_conc_busq               TEXT,
    col_codigo_mat              TEXT,
    col_listas_precios          TEXT,
    col_empty_49                TEXT,
    col_cod_cliente             TEXT,
    col_cod_lista_precio_origen TEXT,
    col_ind_retcl               TEXT,
    col_ind_auto_retcl          TEXT,
    col_fechahora               TEXT,
    col_cod_mot                 TEXT,
    col_tx_motivo               TEXT,
    col_cod_vend                TEXT,
    PRIMARY KEY (_batch_id, _row_number)
);

-- ============================================================
-- STAGING CLEAN: tipos parseados, columnas normalizadas
-- ============================================================

CREATE TABLE IF NOT EXISTS staging.stg_clientes_clean (
    _batch_id               VARCHAR(64)     NOT NULL,
    _row_number             INTEGER         NOT NULL,
    _loaded_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    cod_cliente             VARCHAR(20)     NOT NULL,
    nombre_cliente          TEXT,
    cod_condicion_pago      VARCHAR(20),
    desc_condicion_pago     TEXT,
    cod_ramo_cliente        VARCHAR(20),
    desc_ramo_cliente       TEXT,
    cod_grupo_cliente       VARCHAR(20),
    desc_grupo_cliente      TEXT,
    direccion               TEXT,
    telefono_fijo           VARCHAR(50),
    rif                     VARCHAR(30),
    cod_ruta_transporte     VARCHAR(30),
    poblacion               TEXT,
    cod_zona_ventas         VARCHAR(20),
    desc_zona_ventas        TEXT,
    cod_grupo_vendedor      VARCHAR(20),
    desc_grupo_vendedor     TEXT,
    estado                  TEXT,
    fecha_creacion_cliente  DATE,
    agente_retencion_flag   BOOLEAN,
    num_ultima_factura      VARCHAR(30),
    fecha_ultima_factura    DATE,
    num_ultimo_pago         VARCHAR(30),
    fecha_ultimo_pago       DATE,
    nombre_contacto         TEXT,
    telefono_movil_contacto VARCHAR(50),
    cod_vendedor            VARCHAR(20),
    nombre_vendedor         TEXT,
    cod_gerente_regional    VARCHAR(20),
    nombre_gerente_regional TEXT,
    cod_moneda              VARCHAR(10),
    cod_lista_precio_cliente VARCHAR(20),
    desc_lista_precio_cliente TEXT,
    cod_canal_cliente       VARCHAR(20),
    fecha_corte_archivo     DATE,
    dias_sin_facturar       INTEGER,
    PRIMARY KEY (_batch_id, _row_number)
);

CREATE TABLE IF NOT EXISTS staging.stg_ventas_clean (
    _batch_id               VARCHAR(64)     NOT NULL,
    _row_number             INTEGER         NOT NULL,
    _loaded_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    line_hash               VARCHAR(32)     NOT NULL,
    razon_social            TEXT,
    gpo_cliente             TEXT,
    clase_doc               TEXT,
    num_factura             VARCHAR(30),
    sector                  TEXT,
    canal                   TEXT,
    fecha_doc               DATE,
    zona_vtas               TEXT,
    almacen                 VARCHAR(10),
    denominacion_material   TEXT,
    cantidad_umv            NUMERIC(18,4),
    um_vtas                 VARCHAR(10),
    cantidad_umb            NUMERIC(18,4),
    um_base                 VARCHAR(10),
    prec_unitario           NUMERIC(18,4),
    monto_neto              NUMERIC(18,4),
    iva                     NUMERIC(18,4),
    importe_final           NUMERIC(18,4),
    doc_comercial           TEXT,
    cond_pago               TEXT,
    fec_venc                DATE,
    moneda_doc              VARCHAR(10),
    status_anulacion        VARCHAR(10),
    grp_vend                TEXT,
    vendedor                TEXT,
    referencia              VARCHAR(30),
    pedido_vta              VARCHAR(30),
    jerarquia_1             TEXT,
    jerarquia_2             TEXT,
    jerarquia_3             TEXT,
    um_peso                 VARCHAR(10),
    peso_fact               NUMERIC(18,4),
    um_peso_gen             VARCHAR(20),
    ramo                    TEXT,
    gr_material             TEXT,
    gr_articulo             TEXT,
    tipo_cambio             NUMERIC(18,6),
    mes                     SMALLINT,
    ejercicio               SMALLINT,
    prec_unitario_2         NUMERIC(18,4),
    monto_neto_2            NUMERIC(18,4),
    iva_2                   NUMERIC(18,4),
    importe_final_2         NUMERIC(18,4),
    conc_busq               VARCHAR(30),
    codigo_mat              VARCHAR(20),
    listas_precios          TEXT,
    cod_cliente             VARCHAR(20),
    cod_lista_precio_origen VARCHAR(10),
    ind_retcl               VARCHAR(10),
    ind_auto_retcl          VARCHAR(10),
    fechahora               TIMESTAMPTZ,
    cod_mot                 VARCHAR(10),
    tx_motivo               TEXT,
    cod_vend                VARCHAR(20),
    PRIMARY KEY (_batch_id, _row_number)
);
